//products
export const GETALLPRODUCTS = "GETALLPRODUCTS";
export const GETPRODUCTBYID = "GETPRODUCTBYID";
export const GETPRODUCTBYNAME = "GETPRODUCTBYNAME";
export const DELETEPRODUCT = "DELETEPRODUCT";
export const UPDATEPRODUCT = "UPDATEPRODUCT";
export const CREATEPRODUCT = "CREATEPRODUCT";
